### ISSUE TITLE
Regression in version 3

### ISSUE THREAD

**Issue by martinssipenko** [ghe-actions/dockerfile-validator#4]
The update of Hadolint that was done as part of https://github.com/ghe-actions/dockerfile-validator/pull/3/files has caused a regression because the new binary is missing exec permission on the container.

![image](https://github.com/ghe-actions/dockerfile-validator/assets/598744/e199a213-3cd7-4ea3-b7db-6a3589321c32)

**Comment by gargmukku07** [comment]
Thanks @martinssipenko for identifying this.

**Comment by gargmukku07** [comment]
This is fixed in https://github.com/ghe-actions/dockerfile-validator/pull/5

Please try to use the v4 version and confirm.

**Comment by ss-rstocchi** [comment]
@gargmukku07,

I am still getting the following error:

`/entrypoint.sh: line 6: /hadolint: Permission denied`

When using:

`
      - name: Validate Dockerfile
        uses: ghe-actions/dockerfile-validator@master
        with:
          dockerfile: './Dockerfile'
          lint: 'hadolint'
        if: success()
`
        
or 

`
      - name: Validate Dockerfile
        uses: ghe-actions/dockerfile-validator@v4
        with:
          dockerfile: './Dockerfile'
          lint: 'hadolint'
        if: success()
`

Is adding a "chmod +x" to the Dockerfile for entrypoint needed?

Thanks,

**Comment by ss-rstocchi** [comment]
I've tested the fix of adding `chmod +x` to hadolint and seems to correct the problem. Created #6 .

**Comment by gargmukku07** [comment]
Use the latest one.
